server:
  port: 8761
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 20
spring:
  application:
    name: eureka-server